spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:crud_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    show-sql: true
